<?php
/**
 * @file Functionality associated with Timenesia's memory node
 */

/**
 * Implementation of hook_nodeapi()
 */
function memory_nodeapi(&$node, $op, $a3=NULL, $a4=NULL) {
  if($node->type != 'memory') {
    return;
  }

  switch($op) {
    case 'presave':
      // set the Destination field
      if($node->memory_destination) {
        $node->field_memory_destination[0]['nid'] = $node->memory_destination;
        unset($node->memory_destination);
      }
      break;
  }
}

