<?php
/**
 * @file Enables users to create and access audio blog entries via telephone
 */

foreach (array('audioblog.scripts.inc') as $file) {
  require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . $file);
}

/**
 * Constant definitions
 */

// TODO: move the following constants to the admin/setup area

// General parameters

define('AUDIOBLOG_MAX_STORY_DURATION', 300); // 300 seconds


// Node parameters

define('AUDIOBLOG_NODE_TYPE', 'story');

define('AUDIOBLOG_NODE_PROMOTE', 1);

define('AUDIOBLOG_AUDIO_FIELD_NAME', 'field_audioblog_audio');

define('AUDIOBLOG_TYPE_FIELD_NAME', 'field_audioblog_type');


// Email parameters

define('AUDIOBLOG_EMAIL_SUBJECT', 'New AUDIOBLOG story of type: @audioblog_type');

define('AUDIOBLOG_EMAIL_BODY', "audioblog_type: @audioblog_type,\ncall_id: @call_id,\ncaller_number: @caller_number,\nstart_time: @start_time,\nrecording_url: @recording_url,\nrecording_duration: @recording_duration");


// Audio blog parameters

define('AUDIOBLOG_BLOG_TITLE', 'New audio blog of type: @audioblog_type');

define('AUDIOBLOG_BLOG_BODY', "audioblog_type: @audioblog_type,\ncall_id: @call_id,\ncaller_number: @caller_number,\nstart_time: @start_time,\nrecording_url: @recording_url,\nrecording_duration: @recording_duration");



/**
 * Implementation of hook_perm().
 */
function audioblog_perm() {
  return array('administer audioblog');
}

/*
 * Implementation of hook_menu()
 */
function audioblog_menu() {
  $items = array();

  $items['admin/settings/audioblog'] = array(
    'title' => 'Audioblog',
    'description' => 'audioblog configuration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('audioblog_admin_form', NULL),
    'access arguments' => array('administer audioblog'),
  );

  return $items;
}

function audioblog_admin_form($configuration) {
  $form['audioblog_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Audio blog destination email'),
    '#description' => t("The email address(es) to send the recorded stories to. If empty, no email messages will be sent."),
    '#default_value' => variable_get('audioblog_email', ''),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

function audioblog_admin_form_submit($form, &$form_state) {
  if ($form_state['values']['audioblog_email']) {
    drupal_set_message(t('Story destination email updated.'));
    variable_set('audioblog_email', $form_state['values']['audioblog_email']);
  }
}

/**
 * Process newly recorded audioblog entries
 */
function audioblog_recording_callback($call_id, $recording_url, $recording_duration, $audioblog_type=NULL, $node_type=NULL, $audio_field_name=NULL, $type_field_name=NULL) {

  $rc = TRUE;

  // Log call blast with watchdog
  $log_message = t("(New audioblog recorded) call_id: $call_id, caller_number: $caller_number, start_time: $start_time, recording_url: $recording_url, recording_duration: $recording_duration, audioblog_type: $audioblog_type, node_type: $node_type, audio_field_name: $audio_field_name, type_field_name: $type_field_name");
  watchdog('audioblog', $log_message);

  $cid = VoipCall::getCidFromCallId($call_id);
  $call = VoipCall::load($cid);
  $caller_number = $call->getCallerNumber();
  $start_time = $call->getStartTime();

  $params = array(
                  'call_id'=> $call_id, 
                  'caller_number' => $caller_number,
                  'start_time' => $start_time,
                  'recording_url' => $recording_url, 
                  'recording_duration' => $recording_duration,
                  'audioblog_type' => $audioblog_type,  
                  'node_type' => $node_type,  
                  'audio_field_name' => $audio_field_name,  
                  'type_field_name' => $type_field_name,  
            );

  // send email notification
  $to = variable_get('audioblog_email', NULL);
  if($to) {
    $mail=drupal_mail('audioblog', 'new_recording', $to, language_default(), $params);
    $rc = $mail['result'];
  }

  // create audioblog entry
  if($rc) {
    audioblog_create_audioblog_node($recording_url, $params);
  }
  
  if ($rc){
    return t('Success.');
  }
  else {
    return t('Failure');
  }
}


/**
 * Implementation of hook_mail
 */
function audioblog_mail($key, &$message, $params) {

 switch ($key) {
   case 'new_recording':
     $options = array('@audioblog_type' => $params['audioblog_type'],
                  '@call_id'=> $params['call_id'], 
                  '@caller_number' => $params['caller_number'],
                  '@start_time' => $params['start_time'],
                  '@recording_url' => $params['recording_url'], 
                  '@recording_duration' => $params['recording_duration']);
     $message['subject'] = t(AUDIOBLOG_EMAIL_SUBJECT, $options);
     $message['body'] = t(AUDIOBLOG_EMAIL_BODY, $options);
   break;
  }
}

/**
 * Create an audioblog node
 */
function audioblog_create_audioblog_node($url, $params=array()) {
  $node_type = $params['node_type'];
  $node->type = $node_type ? $node_type : AUDIOBLOG_NODE_TYPE;

  $node->promote = AUDIOBLOG_NODE_PROMOTE;

  $audioblog_type = $params['audioblog_type'];

  $options = array('@audioblog_type' => $audioblog_type,
               '@call_id'=> $params['call_id'], 
               '@caller_number' => $params['caller_number'],
               '@start_time' => $params['start_time'],
               '@recording_url' => $params['recording_url'], 
               '@recording_duration' => $params['recording_duration']);
  $node->title = t(AUDIOBLOG_BLOG_TITLE, $options);
  $node->body = t(AUDIOBLOG_BLOG_BODY, $options);

  if($audioblog_type) { 
//  $node->field_audioblog_type[0]['value'] = $params['audioblog_type'];
    $field_name_tmp = $params['type_field_name'];
    $field_name = $field_name_tmp ? $field_name_tmp : AUDIOBLOG_TYPE_FIELD_NAME;
    if($fieldn_name){
      $field = &$node->$field_name;
      $field[0]['value'] = $audioblog_type;
    }
  }

  $file = _audioblog_transfer_file($url);
  if($file) {
    $field_name_tmp = $params['audio_field_name'];
    $field_name = $field_name_tmp ? $field_name_tmp : AUDIOBLOG_AUDIO_FIELD_NAME;
    $field = &$node->$field_name;
    $field[1]['fid'] = $file['fid'];
  }

  node_save($node);

  return $node;
}

/**
 * Convert URL into an file field
 */
function _audioblog_transfer_file($url, $validators=array()) {
    $filename = rawurldecode(basename($url));
    $filepath = file_create_filename($filename, file_directory_temp());

    // Then make the actual request to download the file.
    $data = file_get_contents($url);

    //Save it to temporary file.
    if ($fp = @fopen($filepath, 'w+')) {
        fputs($fp, $data);
        fclose($fp);
    }

    //Save it to default files directory.
    $destination=file_directory_path();
    $file = field_file_save_file($filepath, $validators, $destination);

    // Delete the temporary file.
    @unlink($filepath);

    if ($file) {
        return $file;
    }

    return NULL;
}

