<?php

/**
 * Constant definitions
 */

// URL of the audio files

define('AUDIOBLOG_ENGLISH', 'http://duke.edu/~ml117/AUDIOBLOG/InteractiveSystem.wavfiles/English/');


/**
 * Prompts
 */

// Messages that appear in more than one script

$invalid_msg = 'Invalid option selected';


// Messages associated with the audioblog_welcome script

$p_welcome_msg = "Welcome to the audio blog system";

// Messages associated with the idepsca_287g_script script

$p_system_description = 'This system will allow you to record and play black audio blog entries';
$p_main_menu = "To record an audioblog entry, press 1. To listen to existing audioblog entries, press 2.";
$p_thank_you = "Thank you for using the audioblog system.";

// Messages associated with the idepsca_287g_record_options script

$p_recording_menu = 'To record a story about the past, Press 1. To record a story about the present, Press 2. To record a story about the future, Press 3.';

// Messages associated with the idepsca_287g_record_story script

$p_recording_prompt = 'Please record your story after the beep.';
$p_recording_confirmation = 'To hear your recording, press 1. To accept your recording, press the pound key. To record once again, press the star key.';
$p_story_accepted = 'Your story has been successfully recorded';

