<?php
/**
 * @file Provides VoIP Drupal functionality for the timenesia project
 */

foreach (array('timenesia_voip.scripts.inc') as $file) {
  require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . $file);
}

/**
 * Implementation of hook_nodeapi()
 */
function timenesia_voip_nodeapi(&$node, $op, $a3=NULL, $a4=NULL) {
  if($node->type != 'memory') {
    return;
  }

  switch($op) {
    case 'presave':
      // set the memory's Destination field
      if($node->memory_destination) {
        $node->field_memory_destination[0]['nid'] = $node->memory_destination;
        unset($node->memory_destination);
      }
      break;
  }
}

