<?php
/**
 * @file Provides VoIP Drupal functionality for the timenesia project
 */

foreach (array('timenesia_voip.scripts.inc') as $file) {
  require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . $file);
}

/**
 * Implementation of hook_nodeapi()
 */
/***
function timenesia_voip_nodeapi(&$node, $op, $teaser=NULL, $page=NULL) {
  if($node->type != 'memory'){
    return;
  }

  switch($op) {
    case "insert":
      $memory_type = $node->audioblog_type;
      if($memory_type) {
        $vocabulary_name = t('When');
        audioblog_save_category($node, $vocabulary_name, $memory_type);
      }
      break;
  }
}

function _audioblog_save_category(&$node, $vocab_name, $term_name) {
  // determine the vocabulary id associated with the given node
  static $vocab_id = NULL;

  if(is_null($vocab_id)) {
    $vocab_id = variable_get('audioblog_vocab_id', NULL); 
    if(is_null($vocab_id)) {
      $vocabs = taxonomy_get_vocabularies($node->type);
      foreach ($vocabs as $vocab_object) {
        if ($vocab_object->name == $vocab_name) {
          $vocab_id = $vocab_object->vid;
          variable_set('audioblog_vocab_id', $vocab_id);
          break;
        }
      }
    }
dsm($vocab_id, 'new vocab_id');
  }

  // determine the term id associated with the term name
  $terms= taxonomy_get_term_by_name($term_name);
dsm($terms, 'terms');
  $tid = NULL;
  foreach($terms as $term) {
    if($term->vid == $vocab_id) {
      $tid = $term->tid;
      break;
    }
  }
dsm($tid, 'tid');

  // save the term id in the node
// $terms[] = $tid;
//  taxonomy_node_save($node, $terms);
  $node->taxonomy[$vocab_id][$tid] = $tid;
//  $node->taxonomy = array($tid);

  return;}
*****/
