<?php

/**
 * Constant definitions
 */


/**
 * Prompts
 */

// Messages that appear in more than one script

$p_invalid_msg = 'Invalid option selected';


// Prompts associated with the timenesia_welcome script

$p_system_greetings = "Welcome to the My Dot Tour system, the best way to engage with the past, the present and the future of Fields Corner. ";

$p_system_menu = "Please type your location number after the beep. For a list of existing locations, press 0. To learn more about the My Dot Tour initiative, press the star key. ";

$p_try_again = 'No input received. Please try again. ';

$p_system_description = 'This system will allow you to record and play back stories about the past, the present and the future of Fields Corner. For additional information about this project, please check our website at my dot tour dot org.';

$p_thank_you = "Thank you for using the My Dot Tour system.";


// Prompts associated with the timenesia_play_destination script

$p_destination_greetings = 'Welcome to destination X. ';

$p_destination_menu = 'To record a story, Press 1. To listen to existing stories, Press 2. To go back to the main menu, press the pound key.';


// Prompts associated with the timenesia_record_options menu

$p_recording_menu = 'To record a story about the past, Press 1. To record a story about the present, Press 2. To record a story about the future, Press 3. To go back to the main menu, press the pound key.';

$p_record_past = 'About to record a story about the past. ';

$p_record_present = 'About to record a story about the present. ';

$p_record_future = 'About to record a story about the future. ';


// Prompts associated with the timenesia_record_memory script

$p_recording_prompt = 'Please record your story after the beep. When done, press the pound key.';
$p_recording_confirmation = 'To hear your recording, press 1. To accept your recording, press 2. To record once again, press the star key.';
$p_recording_playback = 'This is what you recorded: ';
$p_story_accepted = 'Your story has been successfully recorded';

