<?php

/**
 * Constant definitions
 */


/**
 * Prompts
 */

// Messages that appear in more than one script

$p_invalid_msg = 'Invalid option selected';


// Messages associated with the welcome script

$p_welcome_msg = "Welcome to the time nesia system.";

// Messages associated with the idepsca_287g_script script

$p_system_description = 'This system will allow you to record and play black audio blog entries';
$p_main_menu = "Main menu. To record an audio blog entry, press 1. To listen to existing audio blog entries, press 2. To learn more about the time nesia system, press 3.";
$p_thank_you = "Thank you for using the time nesia system.";

// Messages associated with the record_options script

$p_recording_menu = 'Story recording menu. To record a story about the past, Press 1. To record a story about the present, Press 2. To record a story about the future, Press 3. To go back to the main menu, press the pound key.';

// Messages associated with the record_story script

$p_recording_prompt = 'Please record your story after the beep. When done, press the pound key.';
$p_recording_confirmation = 'To hear your recording, press 1. To accept your recording, press 2. To record once again, press 3. To go back to the story recording menu, press the pound key.';
$p_recording_playback = 'This is what you recorded: ';
$p_story_accepted = 'Your story has been successfully recorded';

